src/Entity/Character.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\CharacterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CharacterRepository::class)]
class Character
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: "string", length: 255)]
    #[Assert\Choice(choices: ['Fighter', 'Thief', 'Magic-User', 'Cleric'])]
    private string $class;

    #[ORM\Column(type: "string", length: 255)]
    #[Assert\Choice(choices: ['Human', 'Elf', 'Dwarf', 'Halfling'])]
    private string $species;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $hitpoints = 7;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $max_hitpoints = 7;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $skill_bonus = 1;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $armor_class = 10;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $attack = 1;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $level = 1;

    #[ORM\Column]
    private ?int $XP = 0;

    #[ORM\OneToMany(mappedBy: 'character', targetEntity: Inventory::class, orphanRemoval: true)]
    private Collection $Inventory;

    #[ORM\ManyToOne(inversedBy: 'characters')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function __construct()
    {
        $this->Inventory = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSpecies(): ?string
    {
        return $this->species;
    }

    public function setSpecies(string $species): self
    {
        $this->species = $species;
        $this->applySpeciesModifier();

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(?string $class): self
    {
        $this->class = $class;
        $this->applyClassModifier();

        return $this;
    }

    public function getSkillBonus(): int
    {
        return $this->skill_bonus;
    }

    public function setSkillBonus(int $skill_bonus): self
    {
        $this->skill_bonus = $skill_bonus;

        return $this;
    }

    public function getHitpoints(): ?int
    {
        return $this->hitpoints;
    }

    public function setHitpoints(int $hitpoints): self
    {
        $this->hitpoints = $hitpoints;

        return $this;
    }

    public function getMaxHitpoints(): ?int
    {
        return $this->max_hitpoints;
    }

    public function setMaxHitpoints(int $max_hitpoints): self
    {
        $this->max_hitpoints = $max_hitpoints;

        return $this;
    }

    public function getTempHP(): ?int
    {
        return $this->tempHP;
    }

    public function setTempHP(int $tempHP): self
    {
        $this->tempHP = $tempHP;

        return $this;
    }

    public function getAttack(): ?int
    {
        return $this->attack;
    }

    public function setAttack(?int $attack): void
    {
        $this->attack = $attack;
    }

    public function getArmorClass(): ?int
    {
        return $this->armor_class;
    }

    public function setArmorClass(int $armor_class): self
    {
        $this->armor_class = $armor_class;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getXP(): ?int
    {
        return $this->XP;
    }

    public function setXP(int $XP): self
    {
        $this->XP = $XP;

        return $this;
    }

    /**
     * @return Collection<int, Inventory>
     */
    public function getInventory(): Collection
    {
        return $this->Inventory;
    }

    public function addInventory(Inventory $inventory): self
    {
        if (!$this->Inventory->contains($inventory)) {
            $this->Inventory->add($inventory);
            $inventory->setCharacter($this);
        }

        return $this;
    }

    public function removeInventory(Inventory $inventory): self
    {
        if ($this->Inventory->removeElement($inventory)) {
            // set the owning side to null (unless already changed)
            if ($inventory->getCharacter() === $this) {
                $inventory->setCharacter(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    private function applyClassModifier(): void
    {
        switch ($this->class) {
            case 'Fighter':
                $this->hitpoints += 1;
                $this->attack += 1;
                break;
            case 'Thief':
                $this->skill_bonus += 1;
                $this->armor_class += 1;
                break;
            case 'Magic-User':
                $this->skill_bonus += 2;
                $this->hitpoints -= 1;
                break;
            case 'Cleric':
                $this->hitpoints += 1;
                $this->skill_bonus += 1;
                break;
        }
    }

    private function applySpeciesModifier(): void
    {
        switch ($this->species) {
            case 'Human':
                break;
            case 'Elf':
                $this->skill_bonus += 1;
                $this->hitpoints -= 1;
                break;
            case 'Dwarf':
                $this->hitpoints += 1;
                $this->skill_bonus -= 1;
                break;
            case 'Halfling':
                $this->armor_class += 1;
                $this->attack -= 1;
                break;
        }
    }
}

src/Form/CharacterType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Character;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('hitpoints', IntegerType::class, [
                'disabled' => true,
                'label' => 'Hitpoints',
            ])
            ->add('skill_bonus', IntegerType::class, [
                'disabled' => true,
                'label' => 'Skill Bonus',
            ])
            ->add('armor_class', IntegerType::class, [
                'disabled' => true,
                'label' => 'Armor Class',
            ])
            ->add('attack', IntegerType::class, [
                'disabled' => true,
                'label' => 'Attack',
            ])
            ->add('species', ChoiceType::class, [
                'choices' => [
                    '' => '',
                    'Human (No modifiers)' => 'Human',
                    'Elf (+1 Skill, -1 HP)' => 'Elf',
                    'Dwarf (+1 HP, -1 Skill)' => 'Dwarf',
                    'Halfling (+1 AC, -1 Attack)' => 'Halfling',
                ],
                'choice_attr' => function ($choice, $key, $value) {
                    $descriptions = [
                        '' => '',
                        'Human' => 'No modifiers',
                        'Elf' => '+1 Skill Bonus, -1 Hitpoints',
                        'Dwarf' => '+1 Hitpoints, -1 Skill Bonus',
                        'Halfling' => '+1 Armor Class, -1 Attack',
                    ];
                    return ['data-description' => $descriptions[$value]];
                },
                'required' => true,
            ])
            ->add('class', ChoiceType::class, [
                'choices' => [
                    'Fighter (+1 Attack, ability: Power Strike)' => 'Fighter',
                    'Thief (+1 Skill Bonus, ability: Stealth)' => 'Thief',
                    'Magic-User (+1 Spell Power, ability: Magic Missile)' => 'Magic-User',
                    'Cleric (+1 Healing, ability: Heal)' => 'Cleric',
                ],
                'choice_attr' => function ($choice, $key, $value) {
                    $descriptions = [
                        'Fighter' => '+1 Attack, Special ability: Power Strike',
                        'Thief' => '+1 Skill Bonus, Special ability: Stealth',
                        'Magic-User' => '+1 Spell Power, Special ability: Magic Missile',
                        'Cleric' => '+1 Healing, Special ability: Heal',
                    ];
                    return ['data-description' => $descriptions[$value]];
                },
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Character::class,
        ]);
    }
}

src/Controller/CharacterController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Character;
use App\Form\CharacterType;
use App\Repository\CharacterRepository;
use DiceBag\DiceBag;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CharacterController extends AbstractController
{
    private Security $security;

    private EntityManagerInterface $entityManager;

    public function __construct(Security $security, EntityManagerInterface $entityManager)
    {
        $this->security = $security;
        $this->entityManager = $entityManager;
    }

    #[Route('/character', name: 'character_list')]
    public function index(CharacterRepository $characterRepository): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $characters = $characterRepository->findBy(['user' => $user]);

        return $this->render('character/index.html.twig', [
            'characters' => $characters,
        ]);
    }

    #[Route('/character/new', name: 'character_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $character = new Character();
        $character->setUser($this->security->getUser());

        $this->rollAttributes($character);

        $form = $this->createForm(CharacterType::class, $character);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($character);
            $this->entityManager->flush();

            return $this->redirectToRoute('character_list');
        }

        return $this->render('character/new.html.twig', [
            'character' => $character,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/character/{id}/delete', name: 'character_delete', methods: ['POST'])]
    public function delete(Request $request, Character $character): Response
    {
        if ($this->isCsrfTokenValid('delete' . $character->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($character);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('character_list');
    }

    #[Route('/character/{id}', name: 'character_detail', methods: ['GET'])]
    public function detail(Character $character, Request $request): Response
    {
        // Set the active character for the current user
        $user = $this->getUser();
        $user->setActiveCharacter($character);
        $this->entityManager->persist($user);
        $this->entityManager->flush();

        return $this->render('character/detail.html.twig', [
            'character' => $character,
        ]);
    }

    private function rollAttributes(Character $character): void
    {
        $character->setHitpoints(DiceBag::factory('2d6')->getTotal());
        $modifier = [
            2 => -2,
            3 => -2,
            4 => -1,
            5 => -1,
            6 => 0,
            7 => 0,
            8 => 0,
            9 => 1,
            10 => 1,
            11 => 2,
            12 => 2];
        $character->setSkillBonus($modifier[DiceBag::factory('2d6')->getTotal()]);
        $character->setArmorClass($modifier[DiceBag::factory('2d6')->getTotal()]);
        $character->setAttack($modifier[DiceBag::factory('2d6')->getTotal()]);
    }
}

templates/character/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character Detail: {{ character.name }}{% endblock %}

{% block body %}
    <h1>Character Detail: {{ character.name }}</h1>

    <table class="table">
        <tr>
            <th>Name</th>
            <td>{{ character.name }}</td>
        </tr>
        <tr>
            <th>Species</th>
            <td>{{ character.species }}</td>
        </tr>
        <tr>
            <th>Class</th>
            <td>{{ character.class }}</td>
        </tr>
        <tr>
            <th>Hitpoints</th>
            <td>{{ character.hitpoints }}</td>
        </tr>
        <tr>
            <th>Skill Bonus</th>
            <td>{{ character.skillBonus }}</td>
        </tr>
        <tr>
            <th>Armor Class</th>
            <td>{{ character.armorClass }}</td>
        </tr>
        <tr>
            <th>Attack</th>
            <td>{{ character.attack }}</td>
        </tr>
    </table>

    <a href="{{ path('character_list') }}" class="btn btn-primary">Back to character list</a>
{% endblock %}

templates/character/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character List{% endblock %}

{% block body %}
    <h1>Character List</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Species</th>
            <th>Class</th>
            <th>Hitpoints</th>
            <th>Skill Bonus</th>
            <th>Armor Class</th>
            <th>Attack</th>
        </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr>
                <td>
                    <a href="{{ path('character_detail', {'id': character.id}) }}">{{ character.name }}</a>
                </td>
                <td>{{ character.species }}</td>
                <td>{{ character.class }}</td>
                <td>{{ character.hitpoints }}</td>
                <td>{{ character.skillBonus }}</td>
                <td>{{ character.armorClass }}</td>
                <td>{{ character.attack }}</td>
                <td>
                    <form method="post" action="{{ path('character_delete', {'id': character.id}) }}" onsubmit="return confirm('Are you sure you want to delete this character?');" style="display: inline;">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ character.id) }}">
                        <button class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('character_new') }}" class="btn btn-primary">Create a new character</a>

{% endblock %}

templates/character/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a new character{% endblock %}

{% block body %}
<h1>Create a new character</h1>

    {{ form_start(form) }}

    {{ form_row(form.name) }}
    {{ form_row(form.hitpoints) }}
    {{ form_row(form.skill_bonus) }}
    {{ form_row(form.armor_class) }}
    {{ form_row(form.attack) }}
    {{ form_row(form.species) }}
    <span id="species-description"></span>

    {{ form_row(form.class) }}
    <span id="class-description"></span>

    {{ form_widget(form) }}

    <button class="btn btn-primary">Create</button>
    <a href="{{ path('character_new') }}" class="btn btn-outline-secondary">Re-roll character</a>
    {{ form_end(form) }}

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const speciesSelect = document.getElementById('{{ form.species.vars.id }}');
            const speciesDescription = document.getElementById('species-description');

            function updateSpeciesDescription() {
                const selectedOption = speciesSelect.options[speciesSelect.selectedIndex];
                speciesDescription.textContent = selectedOption.dataset.description;
            }

            speciesSelect.addEventListener('change', updateSpeciesDescription);
            updateSpeciesDescription();

            const classSelect = document.getElementById('{{ form.class.vars.id }}');
            const classDescription = document.getElementById('class-description');

            function updateClassDescription() {
                const selectedOption = classSelect.options[classSelect.selectedIndex];
                classDescription.textContent = selectedOption.dataset.description;
            }

            classSelect.addEventListener('change', updateClassDescription);
            updateClassDescription();
        });
    </script>

{% endblock %}